# config from paper (https://github.com/genforce/genforce/blob/master/configs/stylegan_ffhq256.py)
learning_rate: 0.0001
batch_size: 4
epochs: 10
optimizer: Adam
criterion: BCELoss
image_size: 256
dataset: celebA
model:
  name: TEDIGAN
  parameters:
    beta1: 0.0 #(0.0, 0.99)
    dropout: 0.4
    use_spectral_norm: False
    ngf: 1024
    ndf: 512
    z_channels: 128
device: auto # (cuda / cpu / auto)
experiment_path: ..\experiments
frequencies:
  save_freq: 1 # (i.e. how often should the model checkpoint be saved, in epochs)
  gen_freq: 1 # (i.e. how often should test images be generated, in epochs)
num_imgs: 20 # how many randomly generated images should be saved