# TODO implement eval logic and adapt this template file
mode: eval # (train / eval / gen)
learning_rate: 0.001
batch_size: 1
epochs: 500
optimizer: Adam
criterion: BCELoss
noise_size: 128
image_size: 64
dataset: celebA
model:
  name: CDCGAN
  parameters:
    dropout: 0.2
    alpha: 0.1
    beta1: 0.1
    ngf: 64
    ndf: 64
    z_channels: 128
    use_spectral_norm: False
device: cpu # (cuda / cpu / auto)
experiment_path: ..\experiments
frequencies:
  save_freq: 1 # (i.e. how often should the model checkpoint be saved, in epochs)
  gen_freq: 1 # (i.e. how often should test images be generated, in epochs)
num_imgs: 20 # how many randomly generated images should be saved